In [69]:
# from numpy.random import seed
# seed(1)

In [70]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [71]:
import tensorflow
from tensorflow.keras.models import Sequential

In [72]:
# df = pd.read_csv("train.csv")

# test_df = pd.read_csv("test.csv")
# df = df.dropna(axis="columns", how="all")
# df.dropna()
# test_df = test_df.dropna(axis="columns", how="all")
# test_df.dropna()

In [73]:
#connect to database
engine = create_engine(f"postgres://postgres:postgres@localhost:5432/adoption_db")
conn = engine.connect()

Pet Finder Data

In [74]:
# query data
petfinder= pd.read_sql("select * FROM animal WHERE page is not null AND test_train='train'", conn)
petfinder.dropna()

,id,type,name,age,breed1,breed2,gender,color1,color2,color3,...,photo2_small,photo2_med,status,housetrained,declawed,good_with_kids,good_with_cats,good_with_dogs,url,page
0,70933,1,Rosie,72,72,141,2,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,2.0,0.0,0.0,0.0,1.0,https://www.petfinder.com/dog/rosie-49055592/w...,1219
1,70910,2,Runtsky,84,266,308,1,9,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,1.0,1.0,0.0,https://www.petfinder.com/cat/runtsky-48966170...,1333
3,70919,2,Calvin and Hobbs,12,265,276,1,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,0.0,1.0,1.0,https://www.petfinder.com/cat/calvin-and-hobbs...,1333
4,70922,2,Louie (PAIR WITH FRANKIE),12,266,308,1,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,0.0,1.0,0.0,https://www.petfinder.com/cat/louie-pair-with-...,1333
5,70929,1,Flower,84,187,16,2,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,2.0,0.0,2.0,0.0,1.0,https://www.petfinder.com/dog/flower-49055919/...,1219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69125,70912,2,Oskar,84,266,308,1,2,7,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,1.0,0.0,1.0,0.0,https://www.petfinder.com/cat/oskar-48965929/m...,1333
69126,70915,2,Snow White,12,266,308,2,7,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,0.0,0.0,0.0,https://www.petfinder.com/cat/snow-white-48966...,1333
69127,70918,2,Roxanne,12,266,308,2,10,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,1.0,1.0,1.0,https://www.petfinder.com/cat/roxanne-48966059...,1333
69128,70921,2,Joe,36,265,292,1,2,5,12,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,2.0,0.0,0.0,0.0,https://www.petfinder.com/cat/joe-48965977/wi/...,1333
69129,70928,1,Phigley,36,117,233,1,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,2.0,0.0,0.0,0.0,1.0,https://www.petfinder.com/dog/phigley-49055920...,1219

Kaggle Data

In [75]:
# query data
kaggle_df= pd.read_sql("select * FROM animal WHERE page is null AND test_train='train'", conn)
kaggle_df.head()

,id,type,name,age,breed1,breed2,gender,color1,color2,color3,...,photo2_small,photo2_med,status,housetrained,declawed,good_with_kids,good_with_cats,good_with_dogs,url,page
0,18983,1,Goliath,36,308,308,2,49,49,49,...,None,None,adopted,2.0,0.0,0.0,0.0,0.0,https://www.petfinder.com/dog/goliath-49421185...,None
1,18984,1,Butchy,72,308,308,2,49,49,49,...,None,None,adopted,2.0,0.0,0.0,0.0,0.0,https://www.petfinder.com/dog/butchy-49421141/...,None
2,18966,1,Jackson,12,308,308,2,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,1.0,0.0,1.0,0.0,1.0,https://www.petfinder.com/dog/jackson-49422561...,None
3,18967,1,Milk Dud &#34;FH&#34;,12,308,308,2,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,2.0,0.0,1.0,1.0,1.0,https://www.petfinder.com/dog/milk-dud-and-num...,None
4,18968,1,Charlotte *FH*,12,308,308,2,49,49,49,...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,adopted,2.0,0.0,1.0,1.0,1.0,https://www.petfinder.com/dog/charlotte-star-f...,None

In [76]:
kaggle_df.count()

id                15010
type              15010
name              13753
age               15010
breed1            15010
breed2            15010
gender            15010
color1            15010
color2            15010
color3            15010
maturity_size     15010
furlength         15010
vaccinated        15010
dewormed          15010
sterilized        15010
health            15010
quantity          15010
fee               15010
state_name        15010
rescuer_id        15010
video_amt         15010
description       15009
pet_id            15010
photo_amt         15010
adoption_speed    15010
test_train        15010
photo1_small         19
photo1_med           19
photo2_small         13
photo2_med           13
status            15010
housetrained         19
declawed             19
good_with_kids       19
good_with_cats       19
good_with_dogs       19
url                  19
page                  0
dtype: int64

In [93]:
X = petfinder[["type", "age", "breed1", "breed2", "gender", "color1",
      "color2", "color3", "maturity_size", "furlength", "vaccinated", 
      "dewormed", "sterilized", "health", "fee","photo_amt","video_amt"]]
y = petfinder[["adoption_speed"]]
# X_test = test_df[["type", "age", "breed1", "breed2", "gender", "color1",
#       "color2", "color3", "maturity_size", "furlength", "vaccinated", 
#       "dewormed", "sterilized", "health", "fee","photo_amt","video_amt"]]
# X

       adoption_speed
0                   0
1                   2
2                   0
3                   1
4                   0
...               ...
69125               3
69126               0
69127               2
69128               2
69129               0

[69130 rows x 1 columns]

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0)


X_scaler = MinMaxScaler().fit(X)
X_train_scaled = X_scaler.transform(X)
X_test_scaled = X_scaler.transform(X_test)
                                   
y_train_categorical = to_categorical(y)
y_test_categorical = to_categorical(y_test,5)

In [100]:
y_test_categorical

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [101]:
model=Sequential()

In [102]:
model.add(Dense(units=200, activation='relu', input_dim=17))
model.add(Dense(units=200, activation="relu"))
model.add(Dense(units=200, activation="relu"))
model.add(Dense(units=200, activation="relu"))
model.add(Dense(units=5, activation="softmax")),

(None,)

In [103]:

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

model.fit(X_train_scaled, y_train_categorical, epochs=5, shuffle=True, verbose=2)

Epoch 1/5
2161/2161 - 10s - loss: 0.9898 - accuracy: 0.5250
Epoch 2/5
2161/2161 - 10s - loss: 0.9657 - accuracy: 0.5404
Epoch 3/5
2161/2161 - 12s - loss: 0.9558 - accuracy: 0.5439
Epoch 4/5
2161/2161 - 11s - loss: 0.9518 - accuracy: 0.5444
Epoch 5/5
2161/2161 - 12s - loss: 0.9487 - accuracy: 0.5474

In [104]:
model.predict(X_test_scaled)

array([[7.0543207e-02, 5.1775092e-01, 3.7966260e-01, 3.1995680e-02,
        4.7601152e-05],
       [2.7392143e-02, 3.8913140e-01, 5.1771492e-01, 6.5733247e-02,
        2.8255168e-05],
       [2.8775558e-02, 3.9365244e-01, 5.1312733e-01, 6.4414524e-02,
        3.0107685e-05],
       ...,
       [2.3651764e-01, 4.3133393e-01, 3.0856037e-01, 2.3578821e-02,
        9.3043936e-06],
       [9.1119163e-02, 5.6765550e-01, 3.3200324e-01, 9.2202332e-03,
        1.8959292e-06],
       [7.0091599e-01, 1.4112896e-01, 1.4950450e-01, 8.4505975e-03,
        8.2193159e-09]], dtype=float32)

In [105]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"PetFinder Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

541/541 - 3s - loss: 0.9432 - accuracy: 0.5482
Normal Neural Network - Loss: 0.9432259798049927, Accuracy: 0.5481687188148499